all:

install:
    install -D sig2dot.py $(DESTDIR)/usr/bin/sig2dot
    install -D -m644 doc/sig2dot.1 $(DESTDIR)/usr/share/man/man1/sig2dot.1
    install -D -m644 doc/README \
        $(DESTDIR)/usr/share/doc/signing-party/README.sig2dot

clean:
